name: hcm-pipeline
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pandas>=1.5.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - jupyterlab>=3.4.0
  - rdkit>=2022.09.1
  - biopython>=1.79
  - requests>=2.28.0
  - scipy>=1.9.0
  - scikit-learn>=1.1.0
  - plotly>=5.10.0
  - ipywidgets>=7.7.0
  - pip
  - pip:
    - deepchem>=2.7.1
    - tensorflow>=2.10.0
    - torch>=1.12.0
    - dgl>=0.9.0
    - dgllife>=0.3.0
    # PyRosetta typically requires a manual install or wheel
    # If you have a Rosetta wheel, uncomment and modify:
    # - pyrosetta==2023.X
