name: hcm-pipeline
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyterlab
  - rdkit
  - deepchem
  - biopython
  - requests
  # PyRosetta typically requires a manual install or wheel
  # If you have a Rosetta wheel, you can add it under pip:
  # - pip:
  #   - pyrosetta==2023.X
